### ISSUE TITLE
backend column no exist

### ISSUE THREAD

**Issue by nonorze-VOXX** [PUArallelepiped/PUN-street-Universal-Access#48]
ERRO[0652] pq: column "rate" does not exist             
ERRO[0652] pq: column "rate" does not exist             
ERRO[0652] pq: column "rate" does not exist             
ERRO[0652] pq: column "description" does not exist      
[GIN] 2023/11/06 - 19:21:36 | 500 |     403.592µs |       127.0.0.1 | GET      "/api/v1/store/1"
ERRO[0652] pq: column "description" does not exist      
ERRO[0652] pq: column "description" does not exist      
[GIN] 2023/11/06 - 19:21:36 | 500 |     426.515µs |       127.0.0.1 | GET      "/api/v1/store/1/products"

**Comment by huhuhu0420** [comment]
describe how to trigger the error
